DROP SEQUENCE BOARDSEQ;
DROP TABLE BOARD;

CREATE SEQUENCE BOARDSEQ;

CREATE TABLE BOARD(
	SEQ NUMBER PRIMARY KEY,
	userID VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL,
	hateCount NUMBER
);

CREATE TABLE HATE (
	userID VARCHAR2(100),
	selectID NUMBER,
	userIP VARCHAR2(100)
);

INSERT INTO BOARD VALUES(BOARDSEQ.NEXTVAL, 'RJKE', 'jqweriq', 'dirtjq', SYSDATE);


SELECT * FROM BOARD ORDER BY SEQ;


DROP TABLE MYUSER;
CREATE TABLE MYUSER(
	userID VARCHAR2(100) PRIMARY KEY,
	userPW VARCHAR2(200) ,
	userEMAIL VARCHAR2(200),
	userEMAILHash VARCHAR2(200),
	userEmailChecked CHAR(1),
	CONSTRAINT email_checked CHECK(userEmailChecked IN ('0', '1'))
);

INSERT INTO MYUSER VALUES('ekr123', '123');




