DROP SEQUENCE FREECOMMSEQ;
DROP TABLE FREECOMM;

CREATE SEQUENCE FREECOMMSEQ;

CREATE TABLE FREECOMM(
	FREECOMM_SEQ NUMBER PRIMARY KEY,
	FREECOMM_ID VARCHAR2(500) NOT NULL,
	FREECOMM_TITLE VARCHAR2(500) NOT NULL,
	FREECOMM_CONTENT VARCHAR2(2500) NOT NULL,
	FREECOMM_REGDATE VARCHAR2(100) NOT NULL,
	FREECOMM_READ VARCHAR2(100) NOT NULL
);


INSERT INTO FREECOMM VALUES(FREECOMMSEQ.NEXTVAL, 'user1', '넘버원','첫번째 게시글', '2021-04=01', '0');

SELECT * FROM FREECOMM;