DROP TABLE MYUSER;


CREATE TABLE MYUSER(
	USERID VARCHAR2(100) PRIMARY KEY,
	USERPW VARCHAR2(200) NOT NULL,
	USERNAME VARCHAR2(100) NOT NULL,
	USERGENDER VARCHAR(10) NOT NULL,
	USEREMAIL VARCHAR2(400) NOT NULL,
	USERPROFILE VARCHAR2(400)
);


INSERT INTO MYUSER VALUES('admin', '1234', 'kim', 'm', 'naver', '');


SELECT * FROM MYUSER;