/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-04-04 07:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/0678876332.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".pw {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pw .eyes {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tmargin: auto 2px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// 눈표시 클릭 시 패스워드 보이기 \r\n");
      out.write("\t\t$('.eyes').on('click',function() {\r\n");
      out.write("\t\t\t\t\t$('.pw').toggleClass('active');\r\n");
      out.write("\t\t\t\t\tif ($('.pw').hasClass('active') == true) {\r\n");
      out.write("\t\t\t\t\t\t$(this).find('.fa-eye').attr('class',\"fas fa-eye-slash fa-lg\").parents('.pw')\r\n");
      out.write("\t\t\t\t\t\t\t\t.find('.pw2').attr('type', \"text\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$(this).find('.fa-eye-slash').attr('class',\"fas fa-eye fa-lg\").parents('.pw')\r\n");
      out.write("\t\t\t\t\t\t\t\t.find('.pw2').attr('type', 'password');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t//실시간 아이디 중복\r\n");
      out.write("\tfunction idCheck() {\r\n");
      out.write("\t\tvar userName = $(\"#id\").val();\r\n");
      out.write("\t\tif ($.trim(userName) == \"\" || $.trim(userName) == null) {\r\n");
      out.write("\t\t\t$(\"#idmsg\").text(\"아이디를 입력해주세요\")\r\n");
      out.write("\t\t\t$(\"#idmsg\").css(\"color\", \"red\")\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar queryString = \"?command=idCheck&member_id=\" + userName;\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\turl : 'regist.do' + queryString,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif (data == 0) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#idmsg\").text(\"사용할 수 있는 아이디입니다.\")\r\n");
      out.write("\t\t\t\t\t\t$(\"#idmsg\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#id\").prop(\"title\", \"y\");\r\n");
      out.write("\t\t\t\t\t} else if (data == 1) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#idmsg\").text(\"사용중인 아이디입니다. 다른 아이디를 입력해 주세요\")\r\n");
      out.write("\t\t\t\t\t\t$(\"#idmsg\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#id\").prop(\"title\", \"n\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#idmsg\").text(\"에러에러\");\r\n");
      out.write("\t\t\t\t\t$(\"#idmsg\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t//비밀번호, 비밀번호 확인\r\n");
      out.write("\tfunction passwordCheck() {\r\n");
      out.write("\t\tvar pw = $(\"#pw\").val();\r\n");
      out.write("\t\tvar chkpw = $(\"#chkpw\").val();\r\n");
      out.write("\r\n");
      out.write("\t\tif (chkpw == \"\" && (pw != chkpw || pw == chkpw)) {\r\n");
      out.write("\t\t\t$(\"#pwmsg\").text(\"비밀번호를 입력해주세요\")\r\n");
      out.write("\r\n");
      out.write("\t\t} else if (pw == chkpw) {\r\n");
      out.write("\t\t\t$(\"#pwmsg\").text(\"\");\r\n");
      out.write("\t\t\t$(\"#pw\").prop(\"title\", \"y\");\r\n");
      out.write("\t\t\t$(\"#chkpw\").prop(\"title\", \"y\");\r\n");
      out.write("\t\t} else if (pw != chkpw) {\r\n");
      out.write("\t\t\t$(\"#pwmsg\").text(\"비밀번호가 맞지 않습니다.\");\r\n");
      out.write("\t\t\t$(\"#pwmsg\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t$(\"#pw\").prop(\"title\", \"n\");\r\n");
      out.write("\t\t\t$(\"#chkpw\").prop(\"title\", \"n\");\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Check(){\r\n");
      out.write("\t\tvar email = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#id\").val() == \"\" || $(\"#id\").val() == null){\r\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#pw\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#pw\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#chkpw\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호확인을 해주세요\");\r\n");
      out.write("\t\t\t$(\"#chkpw\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#name\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"이름을 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#name\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#address\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"주소를 입력해주세요\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#phone\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"전화번호를 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#phone\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#email\").val() == \"\"){\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!email.test($(\"#email\").val())){\r\n");
      out.write("\t\t\talert(\"이메일 형식에 맞게 입력해주세요\")\r\n");
      out.write("\t\t\t$(\"#email\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jusoPopup() {\r\n");
      out.write("\t\t//주소검색 수행할 팝업 페이지 호출\r\n");
      out.write("\t\tvar pop = window.open(\"jusoPopup.jsp\", \"pop\",\r\n");
      out.write("\t\t\t\t\"width=570, height=420, scrollbars=yes, resizable=yes\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/** API 서비스 제공항목 확대 (2017.02) **/\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h1>회원가입</h1>\r\n");
      out.write("\t<!-- onsubmit=\"return allCheck();\" -->\r\n");
      out.write("\t<form onsubmit=\"return Check();\" action=\"regist.do\" method=\"post\" >\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"command\" value=\"insertuser\" />\r\n");
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t<td class=\"\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"id\" name=\"member_id\" title=\"n\" onchange=\"idCheck();\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"idmsg\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>비밀번호</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"pw\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"pw\" class=\"pw2\" name=\"member_pw\" title=\"n\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"eyes\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-eye fa-lg\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>비밀번호 확인</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"pw\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"chkpw\" class=\"pw2\" title=\"n\" oninput=\"passwordCheck()\" />\r\n");
      out.write("\t\t\t\t\t<div class=\"eyes\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-eye fa-lg\"></i>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"pwmsg\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"name\" name=\"member_name\" title=\"n\" /></td>\r\n");
      out.write("\t\t\t\t<td id=\"namemsg\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>주소</th>\r\n");
      out.write("                <td>\r\n");
      out.write("                 <div>\r\n");
      out.write("                  \t<input type=\"text\" id=\"zipNo\" name=\"zipNo\" readonly style=\"width:100px\">\r\n");
      out.write("                    <input type=\"button\" value=\"주소검색\" onClick=\"jusoPopup();\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \t<input type=\"text\" id=\"address\" name=\"member_addr\" readonly />\r\n");
      out.write("                </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>전화번호</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"phone\" name=\"member_phone\" title=\"n\" /></td>\r\n");
      out.write("\t\t\t\t<td id=\"phonemsg\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이메일</th>\r\n");
      out.write("\t\t\t\t<td class=\"email\"><input type=\"text\" id=\"email\" name=\"member_email\" title=\"n\" /></td>\r\n");
      out.write("\t\t\t\t<td>예) test@test.com</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"가입하기\" class=\"signbtn\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"메인으로\" class=\"mainbtn\" onclick=\"location.href='regist.do?command=loginForm'\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function jusoCallBack(roadFullAddr,roadAddrPart1,addrDetail,roadAddrPart2,engAddr, jibunAddr, zipNo) {\r\n");
      out.write("\r\n");
      out.write("    var addressEl = document.querySelector(\"#address\");\r\n");
      out.write("    addressEl.value = roadFullAddr;\r\n");
      out.write("    \r\n");
      out.write("\tvar zipNum = document.querySelector(\"#zipNo\");\r\n");
      out.write("\tzipNum.value = zipNo;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
